[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/\.devcontainer/
  | ^/\.github/
  | ^/dev-data/
  | ^/htmlcov/
  | ^/\.pytest_cache/
  | \.backup\.
)
'''